# Generated by Django 5.1.7 on 2025-06-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='entity_type_id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='entity_type_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='entity_type_id',
        ),
        migrations.RemoveField(
            model_name='university',
            name='entity_type_id',
        ),
        migrations.AlterField(
            model_name='adress',
            name='cep',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='adress',
            name='number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='cnpj',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='cpf',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='cpf',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='university',
            name='cnpj',
            field=models.CharField(max_length=20),
        ),
    ]
